web:
   build: .docker/web
   ports:
      - "8080:80"
   volumes:
      - ./html:/var/www/html
   links:
      - db:mysql
db:
   build: .docker/db
   ports:
      - 3306:3306
   environment:
      - MYSQL_DB=magento
      - MYSQL_USER=911labs
      - MYSQL_PASS=911labs
