web:
   build: .docker/web
   ports:
      - "8080:80"
   links:
      - db
db:
   build: .docker/db
   ports:
      - 3306:3306
   environment:
      - MYSQL_DB=magento
      - MYSQL_USER=911labs
      - MYSQL_PASS=911labs
